### ISSUE TITLE
Is short reads data a required input?

### ISSUE THREAD

**Issue by YenlingPeng** [nch-igm/PBFLIP#1]
Can this tool be executed only with PacBio Long reads data?
When I just use pacbio data to execute directly, there will be ILLUMINASHORTREADS KeyError

Also, I have seen short_reads_not_provided.smk in /workflow/rules/

How should it be used? thanks

**Comment by wijerasa** [comment]
You should be able to use the pipeline only with PacBio Long reads. Give me a couple of days to check the error and I will get back to you soon as possible.

**Comment by wijerasa** [comment]
I wasn't able to recreate this error. Are you using the docker image?

**Comment by YenlingPeng** [comment]
I am not using docker to execute, I am running directly on the local machine.

`snakemake -f -p -j 16 -c 16 --latency-wait 20`

Here is a screenshot of the error message
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/63987863/201570245-07f4d6f5-4ec9-4cfd-af80-112bd40cb238.png">

short reads data is to use demo data on [Paper](https://www.jmdjournal.org/article/S1525-1578(22)00265-3/fulltext)

**Comment by wijerasa** [comment]
> I am not using docker to execute, I am running directly on the local machine.
> 
> `snakemake -f -p -j 16 -c 16 --latency-wait 20`
> 
> Here is a screenshot of the error message <img alt="image" width="1093" src="https://user-images.githubusercontent.com/63987863/201570245-07f4d6f5-4ec9-4cfd-af80-112bd40cb238.png">
> 
> short reads data is to use demo data on [Paper](https://www.jmdjournal.org/article/S1525-1578(22)00265-3/fulltext)

Could you remove the short-reads PATHs from the configuration file and re-start the pipeline? If that works I will look into the short-reads section again. Thanks!

**Comment by YenlingPeng** [comment]
Hi,

I remove the short-reads PATHs from the config/case.yml, that's still does not work.

and I got the new ERROR message.

`Traceback (most recent call last):
  File "/home/smrtuser/anaconda3/lib/python3.8/site-packages/snakemake/__init__.py", line 593, in snakemake
    workflow.include(
  File "/home/smrtuser/anaconda3/lib/python3.8/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/data2/PB/BiologyTools/PBFLIP/snakefile", line 156, in <module>
    include: "workflow/rules/summarize_results.smk"
TypeError: 'NoneType' object is not subscriptable`

**Comment by wijerasa** [comment]
> Hi,
> 
> I remove the short-reads PATHs from the config/case.yml, that's still does not work.
> 
> and I got the new ERROR message.
> 
> `Traceback (most recent call last): File "/home/smrtuser/anaconda3/lib/python3.8/site-packages/snakemake/__init__.py", line 593, in snakemake workflow.include( File "/home/smrtuser/anaconda3/lib/python3.8/site-packages/snakemake/workflow.py", line 1182, in include exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals) File "/data2/PB/BiologyTools/PBFLIP/snakefile", line 156, in <module> include: "workflow/rules/summarize_results.smk" TypeError: 'NoneType' object is not subscriptable`

I tried to replicate the issue from my end but I don't see these errors. Could you check each output folder and see if any of those outputs are empty? Most probably this is due to misconfiguration of software dependencies.
